#!/usr/bin/with-contenv /bin/bash

# ------------------------------------------------------------------------------
# Unifi Controller - Init Script
# ------------------------------------------------------------------------------

mkdir /usr/lib/unifi/run
chown unifi:unifi /usr/lib/unifi/run

s6-setuidgid unifi java \
    -Djava.awt.headless=true \
    -Dfile.encoding=UTF-8 \
    "-Xmx${JVM_MAXHEAP}" \
    -jar /usr/lib/unifi/lib/ace.jar \
    start
